version: '3.1'

services:

  hoteldemo-mariadb:
    image: mariadb:jammy
    restart: unless-stopped
    volumes:
      - /home/hoteldemo/data/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: rKVDtv64coi765vBO9n7rwm9bd8in
      MARIADB_USER: hoteldemo
      MARIADB_PASSWORD: 67ajkb235Bnpasg4
      MARIADB_DATABASE: db_hoteldemo

  hoteldemo-php:
    image: hotel-img
    restart: unless-stopped
    ports:
      - 8001:80
#    volumes:
#      - /home/hoteldemo/data/www/:/var/www/html/

  # hoteldemo-adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080